### ISSUE TITLE
currently not working

### ISSUE THREAD

**Issue by dackid19** [Gogomoe/YuyukoMod#1]
game will not load with yuyuko

**Comment by Gogomoe** [comment]
Sorry because of academic pressure I can't update the mod in time.
If you use last version of SlayTheSpire , MTS and basemod, you cannot use my mod.
In fact I have updated YuyukoMod to adapt the last version,but I haven't release the version.

**Comment by Gogomoe** [comment]
I released a  [version v0.2.1a](https://github.com/gogo81745/YuyukoMod/releases/tag/v0.2.1a) just now,it can work
