### ISSUE TITLE
BUG汇报(19-01-24)

### ISSUE THREAD

**Issue by aloneangel34** [Gogomoe/YuyukoMod#12]
1、【从不困惑的亡灵】 这张牌，在使用过后有时会出现被变形的卡牌变形成看不见的卡牌的BUG
（有时候是变成蓝色的牌、可以选中打出但不知道它具体是什么牌；
有时候是变为看不见、选不中打不出但占一个位置的牌）
同时，触发这个BUG以后，回主菜单百科、卡牌总览里看本MOD的所有卡牌时，只要往下拉必定跳出
![uuz](https://user-images.githubusercontent.com/5198120/51655477-d8f6e680-1fd7-11e9-8fe7-e0d7c740401b.png)
![uuz2](https://user-images.githubusercontent.com/5198120/51655478-d98f7d00-1fd7-11e9-8e7f-52df02d06df5.png)

2、初始牌【幻之蝶】和【梦之樱】，不算做攻击、防御，所以在2层事件【古老文字】中无法升级。获得BOSS遗物【潘多拉之盒】时也没有效果。

是故意这样设计的吗？如果不是的话，应该是可以设计成既算作攻击、防御，又能显示个性卡牌名字的。（可以问问觉MOD或者魔理沙MOD的作者，他们是怎么解决的）

3、【对岸的引诱】的英文版，X+!M! 这里出现了问题，“X+”和“!M! ”之间没有插入空格，导致英文版的卡牌描述是没有具体数值的（我是看老外的吐槽里有反馈到这点）
  "Faramita's Temptation": {
    "NAME": "Faramita's Temptation",
    "DESCRIPTION": "Apply 1 Intangible and Fading for each X+!M! HP that enemy has."
},

4、【蓝色和服】遗物，获得的时候会让玩家选形态，选形态是以卡牌的方式显示的。
然而卡牌上的描述不支持 #y #b 这些颜色符号，导致看起来乱七八糟像是乱码。 
（当然选完之后、在遗物列表上的显示是没问题的。主要在于卡牌描述不支持颜色显示，遗物才支持）

5、关于【反魂X（revive）：从消耗堆中查找1张X并加入手牌】描述不准确
描述是说“查找”，那我个人就理解为是可以自己挑的，
比如使用一张带有“反魂蝶”描述的卡，而我消耗堆里面4种衍生蝶都有，那我应该可以自己挑选
然而实际上，这张卡打出后是拿回来的蝶是随机的，没有选择的过程（我确定此时消耗堆里有不同种类、1张以上的蝶）

如果是本来就设计成随机的话，最好把描述改成【反魂X（revive）：从消耗堆中随机将1张X加入手牌】。

**Comment by Gogomoe** [comment]
非常感谢

1 已记录（这个bug以前好像修过的来着，难道漏了……
2 是故意设计的，我认为【幻之蝶】、【梦之樱】不算做【打击】、【防御】，我会去找策划确认一下
3 刚刚有人 pull request 修复了这个
4 为了省事直接这么写的，有时间再修
5 返魂实际上的实现是 拿走符合条件的最先进入消耗堆的那张卡，策划当时是这么指示的

最近学业繁忙，没时间修😂

**Comment by bug-sniper** [comment]
3 is fixed. Thank you for letting me help with the localizations. I'll help with a few more fixes tomorrow.

**Comment by aloneangel34** [comment]
> 2 是故意设计的，我认为【幻之蝶】、【梦之樱】不算做【打击】、【防御】，我会去找策划确认一下
> 5 返魂实际上的实现是 拿走符合条件的最先进入消耗堆的那张卡，策划当时是这么指示的
> 
> 最近学业繁忙，没时间修😂

2、感觉【幻之蝶】、【梦之樱】可以算作打击防御，
我们假设将这两张设计成算作打击防御，
那遇到事件【古老文字】事件群体升级一次、也不会说有什么特别大的影响（和原版的打击防御一样）
而在得到【潘多拉之盒】后、将它们全变掉，要是变得不理想，一下子失去了升级樱和蝶的手段，立马崩盘这点也和游戏本体的骨灰盒设定相一致不是么。

5、那最好就是描述里面说清楚，毕竟难度上去以后是解密游戏
（不断SL，已知行动顺序、发牌顺序，求最优解）
要是一些机制玩家不清楚的话会很困扰的

不过学业还是最优先的，加油吧～！这是个很不错的MOD，个人非常喜欢～
